sudo: required
language: python
python:
    - "3.4"
install: python3 -m pip install -r requirements.txt
env:
    - CONFIG_PATH=blog.config.TravisConfig
before_script:
    - sudo psql -c 'CREATE DATABASE "blogful-test";' -U postgres
    - sudo psql -c 'CREATE USER ubuntu;' -U postgres
    - sudo psql -c 'GRANT ALL PRIVILEGES ON TABLE "users" TO ubuntu;' -U postgres
    - createdb ubuntu
script:
    - PYTHONPATH=. python3 tests/test_filters.py
    - PYTHONPATH=. python3 tests/test_views_integration.py
    - PYTHONPATH=. python3 tests/test_views_acceptance.py
    - PYTHONPATH=. python3 tests/test_binary_file_uploads.py
    # Add any other tests here .